import { StyleSheet } from 'react-native';
import useTheme from '../../theme/index';

const createStyles = () => {
  const {
    colors: {
      gray,
      lightGray,
      greenYellow,
      white,
      black,
      borderGray,
      smoothGray,
      silverWhite,
      ghostGray,
      almostGray,
    },
    fontSizes: { xxs, xs, sm, md, lg, xg, xl, xxg, xxl, lxs, hg, hl },
    margins: { baseMargin },
    paddings: { basePadding },
  } = useTheme();
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: lightGray,
    },
    newBetTitle: {
      marginTop: baseMargin * 2,
      marginBottom: baseMargin * 2,
      color: gray,
      fontSize: xl,
      textTransform: 'uppercase',
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
    newBetPadding: {
      padding: basePadding * 2,
    },
    newBetChooseGame: {
      marginBottom: baseMargin,
      fontStyle: 'italic',
      color: silverWhite,
      fontSize: lg,
    },
    newBetRow: {
      flexDirection: 'row',
    },
    newBetFill: {
      color: silverWhite,
      fontSize: lg,
      fontWeight: 'bold',
      fontStyle: 'italic',
      marginTop: baseMargin * 2,
    },
    newBetFillDescription: {
      color: silverWhite,
      fontSize: sm,
      fontStyle: 'italic',
      paddingRight: basePadding * 5,
    },
    newBetFillDescriptionBold: {
      color: gray,
      fontSize: sm,
      fontStyle: 'italic',
      fontWeight: 'bold',
    },
    newBetBottomLine: {
      borderBottomWidth: 6,
      borderBottomColor: ghostGray,
      borderTopLeftRadius: 4,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 4,
      borderBottomRightRadius: 4,
      width: 36,
    },
    newBetBottomLineCenter: {
      alignItems: 'center',
      marginTop: 10,
      marginBottom: 10,
    },
    newBetRowNumbers: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    newBetButtonsContainer: {
      flexDirection: 'row',
    },
    newBetButtonsLeft: {
      marginRight: baseMargin * 2,
    },
    newBetButtons: {
      backgroundColor: white,
      color: greenYellow,
      borderWidth: 1,
      borderColor: greenYellow,
      padding: basePadding * 0.5,
      marginBottom: baseMargin,
      borderRadius: 5,
      fontWeight: 'bold',
      fontSize: sm,
      flexGrow: 3,
    },
    newBetButtonsCart: {
      backgroundColor: greenYellow,
      color: white,
      borderWidth: 1,
      borderColor: greenYellow,
      padding: basePadding * 0.5,
      marginBottom: baseMargin,
      borderRadius: 5,
      fontWeight: 'bold',
      flexDirection: 'row',
      paddingLeft: basePadding,
      paddingRight: basePadding,
    },
    newBetButtonsAddCart: {
      fontWeight: 'bold',
      color: white,
      fontSize: sm,
      marginLeft: baseMargin,
    },
    newBetNumbers: {
      color: white,
      backgroundColor: almostGray,
      borderRadius: 50,
      fontSize: lg,
      fontWeight: 'bold',
      padding: basePadding * 2,
      margin: baseMargin * 0.6,
    },
    newBetNumbersNumber: {
      color: white,
      fontWeight: 'bold',
    },
    newBetX: {
      margin: -6,
    },
    newBetNumbersMin: {
      color: white,
      backgroundColor: almostGray,
      borderRadius: 50,
      fontSize: sm,
      fontWeight: 'bold',
      marginBottom: baseMargin,
      marginRight: baseMargin,
      paddingLeft: basePadding * 1.3,
      paddingRight: basePadding * 1.3,
      paddingTop: basePadding,
      paddingBottom: basePadding,
      flexDirection: 'row',
    },
    newBetGames: {
      backgroundColor: white,
      flexGrow: 3,
      fontSize: sm,
      borderRadius: 15,
      borderWidth: 1,
      borderColor: black,
      marginRight: baseMargin,
    },
    newBetText: {
      color: black,
      paddingLeft: basePadding * 1.7,
      paddingRight: basePadding * 1.7,
      paddingTop: basePadding * 0.5,
      paddingBottom: basePadding * 0.5,
      flexGrow: 3,
      textAlign: 'center',
      fontWeight: 'bold',
      fontStyle: 'italic',
    },
  });
};

export default createStyles;
